In [1]:
import numpy as np

In [2]:
inputs = np.array([.5, .5, .6, .9])

In [3]:
dense_layer_weights = np.array([[ 0.81835306, -0.23239908,  0.6506299 ,  0.21783918,  0.27162793,
        -0.12351876, -0.16342488, -0.6116278 ],
       [-0.20286793, -0.6403848 , -0.19865394,  0.34566385,  0.05355632,
         0.7617943 ,  0.17708725,  0.3822567 ],
       [ 0.21517096,  0.05956292,  0.00468947,  0.26633084,  0.6261074 ,
        -0.2541544 , -0.02967423, -0.07386237],
       [-0.39198846,  0.4821152 , -0.32181394,  0.36043078,  0.4802994 ,
        -0.18012887, -0.30728677,  0.05972211]])

In [46]:
for weights in dense_layer_weights:
    weights = [weight for weight in weights]
print(dense_layer_weights)

[[ 0.81835306 -0.23239908  0.6506299   0.21783918  0.27162793 -0.12351876
  -0.16342488 -0.6116278 ]
 [-0.20286793 -0.6403848  -0.19865394  0.34566385  0.05355632  0.7617943
   0.17708725  0.3822567 ]
 [ 0.21517096  0.05956292  0.00468947  0.26633084  0.6261074  -0.2541544
  -0.02967423 -0.07386237]
 [-0.39198846  0.4821152  -0.32181394  0.36043078  0.4802994  -0.18012887
  -0.30728677  0.05972211]]


In [4]:
dense_layer_biasis = np.array([ 0.        ,  0.        ,  0.        , -0.17635192, -0.65838534,
        0.33030558,  0.46418095,  0.        ])

In [5]:
dense_layer = inputs.dot(dense_layer_weights) + dense_layer_biasis

In [6]:
dense_layer

array([ 0.08405553,  0.03324949, -0.06083088,  0.5895858 ,  0.31214068,
        0.33483473,  0.1766495 , -0.10525307])

In [7]:
# ReLU Activation function
dense_layer = np.maximum(dense_layer, np.zeros(8))

In [8]:
dense_layer

array([0.08405553, 0.03324949, 0.        , 0.5895858 , 0.31214068,
       0.33483473, 0.1766495 , 0.        ])

In [9]:
output_layer_weights = np.array([[-0.40520093,  0.22385392],
       [-0.6962119 ,  0.09724002],
       [-0.05982208,  0.00445205],
       [-1.0027152 , -0.6188464 ],
       [ 0.27941048,  0.748731  ],
       [ 0.6478007 , -0.39079598],
       [ 0.6618757 ,  0.49175286],
       [-0.16648918,  0.6622045 ]])

array([[-0.73145051,  0.37912003],
       [ 0.27355134,  0.64947415],
       [-0.08160826,  0.23720309],
       [-0.50028843, -0.12158747],
       [-0.40041275, -0.42547235],
       [ 0.02220743, -0.06222732],
       [-0.86023277,  0.777752  ],
       [-0.50640165, -0.3999039 ]])

In [10]:
output_layer_biasis = np.array([0.0, 0.0])

In [11]:
dense_layer

array([0.08405553, 0.03324949, 0.        , 0.5895858 , 0.31214068,
       0.33483473, 0.1766495 , 0.        ])

In [12]:
output_layer = dense_layer.dot(output_layer_weights) + output_layer_biasis

In [13]:
output_layer

array([-0.22735315, -0.15308847])

In [14]:
# Softmax function
output_layer = [np.exp(value) / sum(np.exp(output_layer)) for value in output_layer]

In [15]:
output_layer

[0.4814423579739254, 0.5185576420260746]

In [36]:
np.random.normal(scale=0.5, size=(4,8))

array([[ 0.7062159 , -0.37671933, -1.42455489,  0.43026267, -0.36959533,
        -0.29059966,  0.45647056, -0.47362789],
       [-0.42038319,  0.46465038, -0.25364454,  0.38731073, -0.28123452,
        -0.41551746, -0.3979169 , -0.32534929],
       [-0.74869486,  0.27024656,  0.02878238, -0.2174023 , -0.45635043,
        -0.83173848,  1.06813139,  0.59777182],
       [ 0.69855725,  0.32967414, -0.51495563,  0.74346082, -0.11278412,
        -0.61161409, -0.85431315,  0.57788657]])

In [37]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
from copy import deepcopy

In [70]:
class Brain:
    def __init__(self, parent_brain = None):
        if parent_brain is not None:
            self.copy_parent_brain(parent_brain)
            self.mutate()
        else:
            # Initialize random brain structure
            self.dense_layer_weights = np.random.normal(scale=0.5, size=(4,8))
            self.dense_layer_biases = np.zeros(8)
            self.output_layer_weights = np.random.normal(scale=0.5, size=(8,2))
            self.output_layer_biases = np.zeros(2)
        
    def copy_parent_brain(self, parent_brain):
        self.dense_layer_weights = deepcopy(parent_brain.dense_layer_weights)
        self.dense_layer_biases = deepcopy(parent_brain.dense_layer_biases)
        self.output_layer_weights = deepcopy(parent_brain.output_layer_weights)
        self.output_layer_biases = deepcopy(parent_brain.output_layer_biases)
    
    def mutate(self, mutation_rate, variance_low, variance_high):
        for weight_set in self.dense_layer_weights:
            for weight in weight_set:
                if np.random.random() < mutation_rate:
                    weight = np.random.normal() * np.random.uniform(low=variance_low, high=variance_high)
        for weight in self.dense_layer_biases:
            if np.random.random() < mutation_rate:
                weight = np.random.normal() * np.random.uniform(low=variance_low, high=variance_high)
        for weight_set in self.output_layer_weights:
            for weight in weight_set:
                if np.random.random() < mutation_rate:
                    weight = np.random.normal() * np.random.uniform(low=variance_low, high=variance_high)
        for weight in self.output_layer_biases:
            if np.random.random() < mutation_rate:
                weight = np.random.normal() * np.random.uniform(low=variance_low, high=variance_high)
    
    def predict(self, input_layer):
        dense_layer = input_layer.dot(self.dense_layer_weights) + self.dense_layer_biases
        # ReLU activation
        dense_layer = np.maximum(dense_layer, np.zeros(8))
        output_layer = dense_layer.dot(self.output_layer_weights) + self.output_layer_biases
        # Softmax
        output_layer = [np.exp(value) / sum(np.exp(output_layer)) for value in output_layer]
        print(output_layer)
        return output_layer[0] > output_layer[1]

In [71]:
new_brain = Brain()

In [72]:
new_brain.dense_layer_weights

array([[ 0.80641797,  0.5641356 ,  0.71014113, -0.39176957, -0.23689521,
        -0.78969193,  0.06564181, -0.25393524],
       [-0.59881481, -0.12778103, -0.24195659,  0.15132341, -0.1962933 ,
        -0.70512823, -0.04005461,  0.31713768],
       [ 0.21914894, -0.91829995,  0.65640534,  0.02895018,  0.30449733,
         0.46068046, -0.40435361,  0.96084575],
       [ 1.14211594,  0.03461946, -0.3957016 , -0.06663217, -0.79447243,
         0.18129267, -0.1051021 ,  0.15532289]])